default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    timeout: 5000

development:
    <<: *default
    database: sham_cars_development

test:
    <<: *default
    database: sham_cars_test

production:
    primary: &primary_prod
        <<: *default
        url: <%= ENV["DATABASE_URL"] %>
    cache:
        <<: *primary_prod
        migrations_paths: db/cache_migrate
    queue:
        <<: *primary_prod
        migrations_paths: db/queue_migrate
    cable:
        <<: *primary_prod
        migrations_paths: db/cable_migrate
